In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import ElasticNetCV
from sklearn.model_selection import train_test_split

In [2]:
metadata = pd.read_csv('meta_temporal_pole.csv', sep=';', index_col=0)

In [3]:
metadata

            Age (years)  Gender Condition
acc
SRR9190548           36  Female       MDD
SRR9190515           27    Male   Healthy
SRR9190731           44  Female        SA
SRR9190772           51    Male       MDD
SRR9190614           23  Female   Healthy
...                 ...     ...       ...
SRR9190717           26  Female   Healthy
SRR9190489           40  Female        SA
SRR9190576           32    Male        SA
SRR9190524           27    Male        SA
SRR9190563           21  Female   Healthy

[182 rows x 3 columns]

In [4]:
df = pd.read_csv('train_methylation_temporal_pole.csv', sep=';', index_col=0)

In [5]:
df.head(5)

,SRR9190548,SRR9190515,SRR9190731,SRR9190772,SRR9190614,SRR9190663,SRR9190471,SRR9190536,SRR9190732,SRR9190612,...,SRR9190729,SRR9190475,SRR9190715,SRR9190549,SRR9190788,SRR9190717,SRR9190489,SRR9190576,SRR9190524,SRR9190563
index,,,,,,,,,,,,,,,,,,,,,
10_100007315,6.190000e-01,5.650000e-01,7.690000e-01,4.480000e-01,7.860000e-01,6.920000e-01,8.180000e-01,8.000000e-01,5.620000e-01,1.000000e+00,...,5.000000e-01,6.920000e-01,1.000000e+00,6.920000e-01,6.150000e-01,9.230000e-01,8.080000e-01,8.180000e-01,6.470000e-01,5.000000e-01
10_100007385,7.440000e-01,6.790000e-01,8.000000e-01,5.120000e-01,9.170000e-01,8.330000e-01,6.110000e-01,8.570000e-01,8.180000e-01,9.600000e-01,...,7.500000e-01,8.260000e-01,5.760000e-01,7.180000e-01,9.330000e-01,5.380000e-01,6.590000e-01,7.080000e-01,8.570000e-01,8.850000e-01
10_100007391,9.250000e-01,8.570000e-01,8.500000e-01,9.070000e-01,9.730000e-01,9.500000e-01,8.820000e-01,8.570000e-01,8.710000e-01,9.660000e-01,...,8.850000e-01,8.000000e-01,8.680000e-01,7.950000e-01,9.380000e-01,7.410000e-01,8.040000e-01,8.390000e-01,9.230000e-01,9.580000e-01
10_100007439,8.410000e-01,9.060000e-01,8.000000e-01,7.230000e-01,9.530000e-01,7.080000e-01,9.200000e-01,8.890000e-01,9.520000e-01,8.710000e-01,...,9.690000e-01,8.570000e-01,9.530000e-01,8.330000e-01,9.130000e-01,7.710000e-01,9.260000e-01,8.410000e-01,8.890000e-01,9.330000e-01
10_100007596,9.220000e-01,9.430000e-01,9.380000e-01,9.270000e-01,9.470000e-01,8.810000e-01,8.890000e-01,8.920000e-01,8.540000e-01,9.490000e-01,...,9.680000e-01,9.740000e-01,9.250000e-01,9.810000e-01,9.410000e-01,9.210000e-01,7.920000e-01,9.050000e-01,1.000000e+00,9.750000e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000232124,1.307968e-07,1.514359e-07,6.166738e-08,1.672153e-07,0.000000e+00,9.767794e-08,1.018774e-07,1.792918e-07,1.725998e-07,0.000000e+00,...,0.000000e+00,1.286845e-07,1.212443e-07,9.758751e-08,8.825003e-08,7.140684e-08,1.021776e-07,8.208128e-08,1.390490e-07,1.825734e-07
ENSG00000227999,1.307968e-07,1.730696e-07,0.000000e+00,2.866548e-07,8.277269e-08,1.627966e-08,1.867752e-07,4.482295e-08,1.725998e-07,1.362196e-07,...,4.603947e-07,1.103010e-07,1.616591e-07,1.366225e-07,4.412502e-08,3.570342e-07,3.576214e-07,8.208128e-08,1.853987e-07,1.643161e-07
ENSG00000232539,1.307968e-07,0.000000e+00,0.000000e+00,7.166371e-08,2.276249e-07,1.302373e-07,1.867752e-07,1.120574e-07,2.157497e-07,1.556795e-07,...,8.632400e-08,7.353398e-08,1.414517e-07,7.807001e-08,2.426876e-07,1.249620e-07,1.277219e-07,1.231219e-07,0.000000e+00,1.825734e-08
ENSG00000234509,1.307968e-07,8.653478e-08,0.000000e+00,9.555162e-08,2.069317e-08,1.139576e-07,3.395913e-08,0.000000e+00,4.314994e-08,7.783975e-08,...,0.000000e+00,5.515049e-08,1.414517e-07,0.000000e+00,6.618752e-08,0.000000e+00,1.021776e-07,8.208128e-08,9.269934e-08,5.477202e-08
ENSG00000215386,1.307968e-07,0.000000e+00,0.000000e+00,9.555162e-08,0.000000e+00,6.511863e-08,3.226117e-07,1.120574e-07,4.314994e-08,1.945994e-07,...,3.740707e-07,1.103010e-07,4.041477e-08,2.342100e-07,4.412502e-08,5.355513e-08,7.663317e-08,0.000000e+00,1.390490e-07,3.651468e-08

In [7]:
samples = X.index.intersection(metadata.index)

In [8]:
X = X.loc[samples]
y = metadata.loc[samples, 'Age']

In [9]:
X = X.astype('float32')

In [10]:
y

SRR9190548    36
SRR9190515    27
SRR9190731    44
SRR9190772    51
SRR9190614    23
              ..
SRR9190717    26
SRR9190489    40
SRR9190576    32
SRR9190524    27
SRR9190563    21
Name: Age (years), Length: 182, dtype: int64

In [11]:
X.isnull().sum()

index
10_100007315       0
10_100007385       0
10_100007391       0
10_100007439       0
10_100007596       0
                  ..
ENSG00000232124    0
ENSG00000227999    0
ENSG00000232539    0
ENSG00000234509    0
ENSG00000215386    0
Length: 2605224, dtype: int64

In [12]:
y.isnull().sum()

np.int64(0)

In [13]:
def horvath_transform(age, adult_age=20):
    age = np.array(age)
    return np.where(age <= adult_age, np.log(age+1)-np.log(adult_age + 1), (age - adult_age)/(adult_age+1))

In [14]:
def horvath_inverse(transformed_age, adult_age=20):
    transformed_age = np.array(transformed_age)
    return np.where(transformed_age < 0, np.exp(transformed_age + np.log(adult_age+1))-1, transformed_age * (adult_age+1) + adult_age)

In [15]:
y_transformed = horvath_transform(y)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size=0.2, random_state=42)

In [ ]:
from sklearn.feature_selection import SelectKBest, f_regression

def perform_feature_selection(X, y, k=50000):
    selector = SelectKBest(score_func=f_regression, k=k)
    X_selected = selector.fit_transform(X, y)
    
    selected_features = X.columns[selector.get_support()]
    
    print(f"Final feature count: {X_selected.shape[1]}")
    return X_selected, selected_features

X_reduced, clock_sites = perform_feature_selection(X_train, y_train, k=150000)

In [ ]:
X_train_reduced = X_reduced
X_test_reduced = X_test[clock_sites]

In [ ]:
model = ElasticNetCV(
    l1_ratio=[0.1, 0.5, 0.7, 0.9],
    cv=5,
    alphas=50,
    n_jobs=8,
    max_iter=10000,
    random_state=42
)
model.fit(X_train, y_train)

In [ ]:
preds_transformed = model.predict(X_test_reduced)
preds_years = horvath_inverse(preds_transformed)
actual_years = horvath_inverse(y_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(actual_years, preds_years)
r2 = r2_score(actual_years, preds_years)

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))
plt.scatter(actual_years, preds_years, alpha=0.6, color='teal')
plt.plot([0, 100], [0, 100], 'r--')
plt.title(f"Temporal Pole Clock: MAE = {mae:.2f} years (R² = {r2:.2f})")
plt.xlabel("Chronological Age")
plt.ylabel("Predicted DNAm Age")
plt.show()